[project]
name = "gns3fy"
version = "0.8.0"
description = "Python wrapper around GNS3 Server API"
authors = [{ name = "David Flores", email = "davidflores7_8@hotmail.com"}]
license = "MIT"
readme = "README.md"
repository = "https://github.com/davidban77/gns3fy"
homepage = "https://github.com/davidban77/gns3fy"
keywords = ["network", "gns3", "python", "restapi", "netdev"]
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
requires-python = ">=3.6"

dependencies = [
    "requests>=2.22.0",
    "pydantic>=1.0"
]

[tool.poetry.group.dev.dependencies]
pytest = "^5.0"
flake8 = "^3.7"
requests-mock = "^1.6"
pytest-cov = "^2.7"
mkdocs = "^1.0"
pydoc-markdown = "*"
black = "*"
mkdocs-material = "^6.1.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
